services:
  - type: web
    name: cancunmueve-pwa
    runtime: node
    buildCommand: pnpm install; pnpm run build
    startCommand: npx serve dist
    envVars:
      - key: NODE_VERSION
        value: 20.10.0
