services:
  - type: web
    name: cancunmueve-pwa
    runtime: node
    buildCommand: pnpm run build
    startCommand: node ./dist/server/entry.mjs
    envVars:
      - key: NODE_VERSION
        value: 20.10.0
