# Exported from Render on 2026-02-18T03:54:09Z
version: "1"
projects:
- name: QUINTANAROO_CREATIONS
  environments:
  - name: CANCUNMUEVE
    services:
    - type: web
      name: QueRutaMeLLevaCancun
      runtime: static
      repo: https://github.com/JULIANJUAREZMX01/MueveCancun
      envVars:
      - key: NODE_VERSION
        sync: false
      - key: ENABLE_PNPM
        sync: false
      buildCommand: sh scripts/setup-render.sh
      staticPublishPath: dist
      autoDeployTrigger: checksPass
      previews:
        generation: automatic
