services:
  - type: static_site
    name: muevecancun
    buildCommand: "./scripts/build_render.sh"
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: ENABLE_PNPM
        value: 1
