services:
  - type: web
    name: cancunmueve-pwa
    runtime: node
    buildCommand: pnpm run build
    # Fallback to serving static files if running as a Web Service
    startCommand: npx serve -s dist
    # Explicitly set static publish path for Static Site services
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 20.10.0
