services:
  - type: web
    name: muevecancun
    env: static
    buildCommand: "./scripts/build_render.sh"
    staticPublishPath: ./dist
    branch: main
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: ENABLE_PNPM
        value: 1
